# Generated by Django 2.2.5 on 2019-09-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('ASSET', 'Asset'), ('LIABILILTY', 'Liability'), ('EQUITY', 'Equity'), ('COGS', 'COGS')], max_length=12)),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
    ]
