# Generated by Django 2.2.5 on 2019-09-14 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(max_length=200)),
                ('ref_number', models.CharField(max_length=200)),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('transactiondate', models.DateTimeField(auto_now_add=True, verbose_name='transaction date')),
            ],
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Transaction')),
            ],
        ),
    ]
